name: Deploy Online Test Platform

on:
  push:
    branches:
      - main
      - copilot/fix-56064056-2d00-47cb-8e45-e455bf7c1368
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./Online Test Platform"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
